[package]
name = "web_scrapper_tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
futures = "0.3"

crossbeam-utils = "0.8"
